name: Matrix-CI-CD

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.11]
        os: [windows-latest, ubuntu-latest, macos-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python main.py
