name: Deploy
on:
  push:
    branches:
      - dev  # Adjust this to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
          
      - name: Connect to remote server and run command
        run: |
          ssh-keyscan "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts
          ssh "${{ secrets.USER }}"@"${{ secrets.SERVER_IP }}" "cd /home/ubuntu/ && ls -al && touch new.php && ls -al"
